<?php
/**
 * EvaluationBatchResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Justpark\Flagr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Justpark\Flagr;

/**
 * EvaluationBatchResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description EvaluationBatchResponse
/**
 * @package     Justpark\Flagr
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvaluationBatchResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvaluationBatchResponse"
     */
    public function testEvaluationBatchResponse()
    {
    }

    /**
     * Test attribute "evaluation_results"
     */
    public function testPropertyEvaluationResults()
    {
    }
}
