<?php
/**
 * EvalResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EvalResultTest Class Doc Comment
 *
 * @category    Class */
// * @description EvalResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvalResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvalResult"
     */
    public function testEvalResult()
    {
    }

    /**
     * Test attribute "flag_id"
     */
    public function testPropertyFlagId()
    {
    }

    /**
     * Test attribute "flag_key"
     */
    public function testPropertyFlagKey()
    {
    }

    /**
     * Test attribute "flag_snapshot_id"
     */
    public function testPropertyFlagSnapshotId()
    {
    }

    /**
     * Test attribute "segment_id"
     */
    public function testPropertySegmentId()
    {
    }

    /**
     * Test attribute "variant_id"
     */
    public function testPropertyVariantId()
    {
    }

    /**
     * Test attribute "variant_key"
     */
    public function testPropertyVariantKey()
    {
    }

    /**
     * Test attribute "variant_attachment"
     */
    public function testPropertyVariantAttachment()
    {
    }

    /**
     * Test attribute "eval_context"
     */
    public function testPropertyEvalContext()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "eval_debug_log"
     */
    public function testPropertyEvalDebugLog()
    {
    }
}
