<?php
/**
 * PutFlagRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  JustPark\Flagr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace JustPark\Flagr;

/**
 * PutFlagRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description PutFlagRequest
/**
 * @package     JustPark\Flagr
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PutFlagRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PutFlagRequest"
     */
    public function testPutFlagRequest()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "data_records_enabled"
     */
    public function testPropertyDataRecordsEnabled()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }
}
